### ISSUE TITLE
Usage with an anaconda environment

### ISSUE THREAD

**Issue by grisaitis** [freeman-lab/spark-janelia#19]
How do I tell pyspark to use a certain anaconda environment when executing my python code?

My code has some non-python dependencies that I have in an anaconda environment, but the spark workers of course don't know about them. I've tried explicitly passing environment variables like PYSPARK_PYTHON or PATH when calling `spark-janelia lsd`, but that doesn't seem to change anything. My anaconda's `bin/` is the first thing in my `$PATH`.

**Comment by freeman-lab** [comment]
i think @d-v-b has a solution for this?

**Comment by d-v-b** [comment]
here's my bash profile which has the relevant vars: https://gist.github.com/d-v-b/32fd8e040b25d27e6971

**Comment by grisaitis** [comment]
Thanks! I'll try this. 

Do you know of an alternative to editing my bash profile? I'm wondering if I can give `lsd` a shell script instead of a python script, where the shell script defines my environment and calls the python script.
