### ISSUE TITLE
cluster upgrade

### ISSUE THREAD

**Issue by jwittenbach** [freeman-lab/spark-janelia#23]
The spark nodes on the clusters are being upgraded to a new operating system soon. I ran some tests on a few test nodes that have the upgrade completed today. The changes will require some updates to the `spark-janelia` scripts, so I wanted to document these here so we have the info when the time comes.
1. The new operating system has an upgraded version of Python on it. Our scripts specify directly which version of python to use. We will need to change all reference from `Python-2.7.6` to `Python-2.7.11`.
2. Network installed software now lives in `/misc` instead of `/local`, so we will need to change that as well. For us, this includes Python and Spark.
3. The newer version of `Python 2.7` now uses `jupyter notebook` instead of `ipython notebook` to access the notebook. One nice feature of this is that we should be able to now remove `setup-notebook-janelia`. This is because the `jupyter` CLI allows setting any configuration we like at the command line, thus making a config file unnecessary. The following will now work for spinning up a notebook server:
   
   ``` bash
   IPYTHON=1 IPYTHON_OPTS="notebook --port 9999 --ip '*' --no-browser" /path/to/pyspark
   ```
   
   This seems better, as it allows users to manage their on notebook config file for non-Spark usage and then we can override those settings for `spark-janelia start`.

**Comment by jwittenbach** [comment]
@freeman-lab @d-v-b @boazmohar might find this info useful

**Comment by nvladimus** [comment]
@jwittenbach thanks for the update, it is very useful in planning my experiments :) When will the cluster update start affecting us, users?

**Comment by jwittenbach** [comment]
@nvladimus glad it helps :) All I've heard about timing is that the full upgrade will take place sometime in the next month. I'll keep my ears open and, as soon as I hear about it, I'll make a PR to get everything with `spark-janelia` running as before ASAP.

**Comment by nvladimus** [comment]
Thanks for being alert! :) I will be glad to test the code on my side, too - just let me know when ready.

**Comment by jwittenbach** [comment]
@nvladimus from an email from Ken:

"we will be upgrading all Spark nodes in one week."

**Comment by nvladimus** [comment]
Oh, boy...

**Comment by mikarubi** [comment]
My spark configuration is no longer working, but was working just a couple
of days ago. it must be the same problem we ran into with Virginia...

**Comment by nvladimus** [comment]
I am trying to config the jupyter and get an error:
```
jupyter notebook --generate-config
/misc/local/python-2.7.11/bin/python: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /misc/                      local/python-2.7.11/bin/python)
```
Anyone had the same issue?

**Comment by jwittenbach** [comment]
@nvladimus are you in the "Spark test group" that Ken mentions in his latest emails? If not, then you'll still be getting nodes for your Spark cluster that are running the older operating system, SL6. This means that you then need you make sure that your driver is also running SL6. As of a couple of days ago, the default for `qlogin` requests will put you on an SL7 node. Try the following:
1. Verify that `which python` points to the cluster's old Python install: `/urs/local/python-2.7.6/bin/python`
2. Launch your cluster with `spark-janelia launch -n [N]` as usual
3. Instead of using `spark-janelia login`, manually request an SL6 node for your driver with `qlogin -pe batch 16 -l sl6=true -l interactive=true` (I'm not sure if you need the `-l interactive=true`, so if it doesn't work, then try dropping that).
4. We need to do one other thing by hand that `spark-janelia login` usually takes care of. Run `qstat` to find the name of your master node (`hXXuXX`) and now run `echo spark://hXXuXX:7077 > ~/spark-master`.
5. Finally, try running the usual `spark-janelia start`.

Once they finish the upgrade next Wednesday, I'll update the `spark-janelia` script to work with the new configuration.

**Comment by nvladimus** [comment]
I went up to this point:

```
[vladimirovn@h06u12 ~]$ spark-janelia start -b

View your notebooks at http://h06u12.int.janelia.org:9999
View the status of your cluster at http://h01u03.int.janelia.org:8080

/usr/local/spark-current//bin/spark-class: line 86: /usr/local/jdk1.8.0_45/bin/java: No such file or directory
```

**Comment by nvladimus** [comment]
@jwittenbach  yes, I am in the test group, Ken added me.

**Comment by jwittenbach** [comment]
@nvladimus ah, ignore everything I just said then 😸

**Comment by nvladimus** [comment]
@jwittenbach thanks for fixing! :+1:

**Comment by nvladimus** [comment]
Weird.. When trying to launch a cluster again, the whole thing stopped working:

```
[login1 - vladimirovn@e05u03]~>spark-janelia launch-in -n 2
/misc/local/python-2.7.11/bin/python2.7: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /misc/local/python-2.7.11/bin/python2.7)
```

**Comment by nvladimus** [comment]
OK, I found a way around, from Ken's email: `qlogin -pe batch 16 -l interactive=true -now n`

**Comment by nvladimus** [comment]
A piece of code which became obsolete is adding external python functions to the context:

```
sc.addPyFile('/.../code/importEphys.py')
NameError: name 'sc' is not defined
```

**Comment by nvladimus** [comment]
The way to fix this:

```
import sys
sys.path.append('/.../code')
import fileName
```

**Comment by nvladimus** [comment]
Another issue is how to do operations like 

```
fileList = glob.glob(rawDir + 'TM*.stack.bz2')
sc.parallelize(fileList).foreach(bz2uncompressStack)
```

when `sc` is not defined?

**Comment by nvladimus** [comment]
Well, looks like notebook server is working, but Spark is not.

**Comment by jwittenbach** [comment]
As long as you use the second login node on the cluster, every node that you interact with should now default to the upgraded OS. Since this is finally the case, I went ahead and updated the `spark-janelia` script to work in the new environment.

The only change you will need to make is to go into your `.bash_profile` and update your `PATH` to contain `python-2.7.11` now instead of `python-2.7.6`.
