### ISSUE TITLE
example ipynb does not work completely

### ISSUE THREAD

**Issue by carlilek** [freeman-lab/spark-janelia#27]
At step 16, it throws this error: 

NameError                                 Traceback (most recent call last)
<ipython-input-16-202bab258851> in <module>()
      2 xy = np.asarray(xy)
      3 
----> 4 plt.scatter(xy[:,0], xy[:,1]);

NameError: name 'plt' is not defined

**Comment by d-v-b** [comment]
gotta add `import matplotlib.pyplot as plt` I assume

**Comment by jwittenbach** [comment]
yeah, that should be it

**Comment by jwittenbach** [comment]
Just went through the example notebook. There were a couple of other errors, so I fixed those as well. Hopefully it should run all the way through now with no hitches _finger crossed_

**Comment by carlilek** [comment]
Thanks, guys!

--Ken

Sent from my <advertising redacted>

On Nov 18, 2016, at 2:36 PM, Jason Wittenbach notifications@github.com wrote:

Just went through the example notebook. There were a couple of other errors, so I fixed those as well. Hopefully it should run all the way through now with no hitches
finger crossed
�
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/freeman-lab/spark-janelia","title":"freeman-lab/spark-janelia","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/freeman-lab/spark-janelia"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jwittenbach in #27: Just went through the example notebook. There were a couple of other errors, so I fixed those as well. Hopefully it should run all the way through now with no hitches _finger crossed_"}],"action":{"name":"View Issue","url":"https://github.com/freeman-lab/spark-janelia/issues/27#issuecomment-261648199"}}}
